from hardware import *
import sys



def actionButton_Callback(directCommand):


    hardware=directCommand.parent.hardware

    dispensePumps(hardware,[180,50,75,90,75,25],[1,2,3,4,5,6,7,8],[],[],[],[],[],0)
    #goToWell(hardware,"DB",1,0)
    #multiDispensePumps(hardware,[200,25,25,0,0,0])
    #ElongationAether(hardware,0)
    #hardware.vacuum.start()
    #ElongationCycle(hardware,0)
    #waitAndStir(hardware,10*60)
    #FJTaqman(hardware,0)
    #FJCodonMap(hardware,0)
    #ElongationCycleSeparatedOneEnz(hardware,0)
    #ElongationCycleSeparatedTwoEnz_384Test(hardware,1)
    #ElongationCycleSeparatedTwoEnz(hardware, 0)
    #ElongationCycleTwoEnzymesWithWater(hardware, 0)
    #ElongationCycleNGS(hardware,0)
    #ElongationTimesTwoEnzymes(hardware,0)
    #ElongationCycleDiffVolumes(hardware,1)
    #ElongationCycleDiffDBTimes(hardware,0)
    #ElongationCycleDiffElongTimes(hardware,0)
    #goToWell(hardware,'A',92,1)
    #dispense(hardware,'DB',0.055*2)
    #goToWell(hardware,'DB',1,4)
    #dispense(hardware,'M',0.28)
    #dispense(hardware, 'BB', 0.18)
    #multiDispense(hardware,[1,1,1,1],15)
    #wells=list(range(1,96,1))
    #dispensePremixes(hardware,0.2,[1,5],[2,6],[3,7],[4,8],1)
    #dispensePremixes(hardware,0.24,[],[],[],[x*4+1 for x in list(range(24))],0)
    #dispenseWashes(hardware,0.17,"BB",[33,37,41,45,49,53,57,61])
    #dispensePremixesAndEnzyme(hardware, 0.2, list(range(1,97)), [], [], [], [], [], 0)
    #multiDispenseWithEnzyme(hardware,[0,1,0,0,0,1],0.4,0.4)
    #goToWell(hardware, 'thermalCamera', 1)
    #goToWell(hardware,'M',9,0)
    #dispense(hardware,"M",0.3)
    #cloggingTest(hardware)
    #removeSupernatant(hardware,10)
    #supernatantRemovalTest(hardware,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
    #dispensePremixes(hardware,0.18,[1,5,9,13,17,21,25],[1+1,5+1,9+1,13+1,17+1,21+1,26+1],[1+2,5+2,9+2,13+2,17+2,21+2,26+2],[1+3,5+3,9+3,13+3,17+3,21+3,26+3])
    #directCommand.parent.hardware.goToWell(16)
    #polyTCycles(hardware,[1,2,3,4,5,6,7,8])
    #washProcedure(hardware)
    #crashtest(hardware)
    #hardware.vacuum.start()
    #waitAndStir(hardware,30)
    #removeSupernatant(hardware,15)
    #goToWell(hardware,'A',1)
    #dispenseInPlate(hardware)
    #goToWell(directCommand.parent.hardware,"BB",9)
    #initialiseMotorList(hardware, [hardware.stirrerMotor])
    #initialiseMotorList(hardware, [hardware.magnetMotor])
    #hardware.stirrerMotor.move_absolute(-5000)
    #magnetGoUp(directCommand.parent.hardware)
    #magnetGoDown(directCommand.parent.hardware)
    #magnetGoUp(directCommand.parent.hardware)
    #directCommand.parent.hardware.stirrerMotor.move_absolute(-5000)
    #needlesGoDown(hardware)
    #hardware.arduinoControl.startHeating()
    #thermalMap(hardware).16, 'DB', list(range(33,65+1,1)))
    #goToWell(hardware,'thermalCamera',1)
    #goToWell(hardware,"A",1)
    #bugTest(hardware)
    #PrimingVolume(hardware)
    #ThermalTest(hardware)

